    <footer class="bg-blue-800 max-lg:hidden  ">
        <div class="flex flex-row justify-center ">
            <div class="flex flex-col mr-8">
                <div class=" flex flex-col">
                    <img src="./src/images/brand-lego.svg.png" alt="Logo" class="max-w-28">
                    <div class="flex items-center pt-4 ">
                        <div
                            class="flex justify-center items-center max-w-32 pr-4   text-white bg-blue-950 text-center p-2">
                            <img src="./src/images/map.png" alt="map" class="max-w-6 mr-4 ">France
                        </div>
                    </div>
                </div>
                <div>
                    <ul class="text-white font-medium leading-10 mb-4">
                        <li><a href="#">Cartes-cadeaux</a></li>
                        <li><a href="#">Trouve de l'inspiration</a></li>
                        <li><a href="#">Catalogues LEGO</a></li>
                        <li><a href="#">Trouver un LEGO Store</a></li>
                    </ul>
                </div>
            </div>



            <div class="p-6 flex flex-row justify-between text-white">
                <div class="mb-6 mr-8 ">
                    <span class="font-bold">À PROPOS DE NOUS</span>
                    <ul>
                        <li class="">
                            <a href="#" class="block py-2 px-4 hover:bg-blue-800">À propos du Groupe LEGO</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 hover:bg-blue-800">Nouveautés LEGO®</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 hover:bg-blue-800">Durabilité</a>
                        </li>
                        <li class="max-w-56">
                            <a href="#" class="block py-2 px-4 hover:bg-blue-800">Déclaration de transparence de la
                                chaîne logistique</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 hover:bg-blue-800">Certification produit LEGO</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 hover:bg-blue-800">Emplois LEGO</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 hover:bg-blue-800">LEGO compliance line</a>
                        </li>
                    </ul>
                </div>

                <div class="mb-6 mr-8 ">
                    <span class="font-bold">AIDE</span>
                    <ul>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">Contactez-nous</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">Instructions de montage</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">Pièces manquantes</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">Expedition et retours</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">mode de paiement </a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">Conditions génerales</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">Rappels de produit</a>
                        </li>
                    </ul>
                </div>
                <div class="mb-6 mr-8 ">
                    <span class="font-bold">ATTRACTIONS</span>
                    <ul>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">LEGO House</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">LEGOLAND Parks</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">LEGOLAND Discovery Centers</a>
                        </li>
                    </ul>
                </div>


                <div class="mb-6  mr-8">
                    <span class="font-bold">ALLER PLUS LOIN AVEC NOUS</span>
                    <ul>
                        <li class="">
                        <li class=" ">
                            <a href="#" class="block py-2 px-4 ">LEGO Magazine (GRATUIT)</a>
                        </li>
                        <li class=" ">
                            <a href="#" class="block py-2 px-4 ">LEGO Education</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">LEGO Ideas</a>
                        </li>
                        <li class="">
                            <a href="#" class="block py-2 px-4 ">LEGO foundation</a>
                        </li>
                        <a href="#" class="block py-2 px-4 ">Programme d'affilation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="flex justify-evenly flex-row">
            <div>
                <h4 class="text-white font-medium text-base pb-2 ">S'ABONNER AUX E-MAILS DE MARKETING NUMERIQUE</h4>
                <div class="flex flex-row  text-black"><input type="text" class="p-4 " placeholder="Ton adresse e-mail">
                    <img src="./src/images/chevron.svg" alt="Chevron" class=" rounded-e-xl p-4 bg-orange-600 ">
                </div>
            </div>

            <div class="ml-8">
                <h6 class="text-white font-medium text-lg pb-4">Suis-nous</h6>
                <div class="flex flex-row justify-start items-center">
                    <img src="./src/images/Facebook.png" alt="Facebook"
                        class="bg-white rounded-full  max-w-10 max-h-10 mr-4">
                    <img src="./src/images//X.png" alt="Twitter" class=" bg-white rounded-full max-w-10 max-h-10 mr-4">
                    <img src="./src/images//insta.png" alt="Instagram"
                        class=" bg-white rounded-full max-w-10 max-h-10 mr-4">
                    <img src="./src/images/Youtube.png" alt="Youtube"
                        class=" bg-white rounded-full max-w-10 max-h-10 mr-4">
                </div>
            </div>
        </div>
        <div class="flex ">
            <ul class="text-white text-xs flex flex-row ml-24 mt-10 justify-between  ">
                <li class="pt-4 pr-2">Vie privée</li>
                <li class="pt-4 pr-2">Cookies</li>
                <li class="pt-4 pr-2"> Mentions légales</li>
                <li class="pt-4 pr-2"> Conditions d'utilisation</li>
                <li class="pt-4 pr-2">Accessibilité</li>
                <li class="pt-4 ">Configuration des cookies</li>
            </ul>
        </div>
        <div class=" flex justify-center">
            <p class="text-white text-xs  text-center pt-10 p-b-10">LEGO System A/S, DK-7190 Billund, Denmark. Vous
                devez
                être
                âgé(e) d’au
                moins 18
                ans pour
                faire des achats en
                ligne. LEGO, le logo LEGO, la Minifigure, DUPLO, le logo FRIENDS, le logo MINIFIGURES, le DREAMZzz,
                NINJAGO,
                VIDIYO et MINDSTORMS sont des marques déposées du Groupe LEGO. ©2024 The LEGO Group. Tous droits
                réservés.
                L'utilisation de ce site implique que vous acceptez les conditions d'utilisation.</p>
        </div>

    </footer>










    <footer class="lg:hidden   bg-blue-800 ">
        <div class=" flex flex-row">
            <img src="./src/images/brand-lego.svg.png" alt="Logo" class="max-w-14">
            <div class="flex items-start pl-2">
                <div class="flex justify-center items-center max-w-32  text-white bg-blue-950 text-center p-2"><img
                        src="./src/images/map.png" alt="map" class="max-w-6 mr-4 ">France
                </div>
            </div>
        </div>
        <div>
            <ul class="text-white font-medium leading-10 mb-4">
                <li><a href="#">Cartes-cadeaux</a></li>
                <li><a href="#">Trouve de l'inspiration</a></li>
                <li><a href="#">Catalogues LEGO</a></li>
                <li><a href="#">Trouver un LEGO Store</a></li>
            </ul>
        </div>
        <div>
            <h4 class="text-white font-medium">S'ABONNER AUX E-MAILS DE MARKETING NUMERIQUE</h4>
            <div class="flex flex-row justify-center p-4"><input type="text" class="p-4 pr-52"
                    placeholder="Ton adresse e-mail">
                <img src="./src/images/chevron.svg" alt="Chevron" class=" rounded-e-xl p-4 bg-orange-600 ">
            </div>
        </div>


        <div class="p-6 text-white">

            <div class="mb-6 pl-4   ">
                <button id="footerMenu" data-name='about-menu' class="flex flex-row  "
                    class="flex justify-between w-full py-3 px-4 bg-blue-800  focus:outline-none">

                    <span class="font-bold">À PROPOS DE NOUS</span>
                    <span id="about-arrow" class="ml-4">&#9660;</span>

                </button>
                <ul id="about-menu" class="bg-blue-800 text-lg">
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 hover:bg-blue-800">À propos du Groupe LEGO</a>
                    </li>
                    <li class="border-b  border-white">
                        <a href="#" class="block py-2 px-4 hover:bg-blue-800">Nouveautés LEGO®</a>
                    </li>
                    <li class="border-b  border-white">
                        <a href="#" class="block py-2 px-4 hover:bg-blue-800">Durabilité</a>
                    </li>
                    <li class="border-b  border-white0">
                        <a href="#" class="block py-2 px-4 hover:bg-blue-800">Déclaration de transparence de la
                            chaîne logistique</a>
                    </li>
                    <li class="border-b  border-white">
                        <a href="#" class="block py-2 px-4 hover:bg-blue-800">Certification produit LEGO</a>
                    </li>
                    <li class="border-b  border-white">
                        <a href="#" class="block py-2 px-4 hover:bg-blue-800">Emplois LEGO</a>
                    </li>
                    <li class="border-b  border-white">
                        <a href="#" class="block py-2 px-4 hover:bg-blue-800">LEGO compliance line</a>
                    </li>
                </ul>
            </div>

            <div class="mb-6 ">
                <button id="footerMenu" data-name='help-menu' class="flex justify-between w-full py-3 px-4 bg-blue-800  focus:outline-none">
                    <span class="font-bold">AIDE</span>
                    <span id="help-arrow" class="ml-4">&#9660;</span>
                </button>
                <ul id="help-menu" class="hidden bg-blue-800 text-lg">

                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">Contactez-nous</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">Instructions de montage</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">Pièces manquantes</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">Expedition et retours</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">mode de paiement </a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">Conditions génerales</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">Rappels de produit</a>
                    </li>

                </ul>
            </div>

            <div class="mb-6 ">
                <button id="footerMenu" data-name='attractions-menu'
                    class="flex justify-between w-full py-3 px-4 bg-blue-800  focus:outline-none">
                    <span class="font-bold">ATTRACTIONS</span>
                    <span id="attractions-arrow" class="ml-4">&#9660;</span>
                </button>
                <ul id="attractions-menu" class="hidden bg-blue-800 text-lg">
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">LEGO House</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">LEGOLAND Parks</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">LEGOLAND Discovery Centers</a>
                    </li>

                </ul>
            </div>


            <div class="mb-6 ">
                <button id="footerMenu" data-name='more-menu' class="flex justify-between w-full py-3 px-4 bg-blue-800 focus:outline-none">
                    <span class="font-bold">ALLER PLUS LOIN AVEC NOUS</span>
                    <span id="more-arrow" class="ml-4">&#9660;</span>
                </button>
                <ul id="more-menu" class="hidden bg-blue-800 text-lg">
                    <li class="border-b border-white">
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">LEGO Magazine (GRATUIT)</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">LEGO Education</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">LEGO Ideas</a>
                    </li>
                    <li class="border-b border-white">
                        <a href="#" class="block py-2 px-4 ">LEGO foundation</a>
                    </li>
                    <a href="#" class="block py-2 px-4 ">Programme d'affilation</a>
                    </li>

                </ul>
            </div>
        </div>

        <div class="ml-8">
            <h6 class="text-white font-medium text-lg pb-4">Suis-nous</h6>
            <div class="flex flex-row justify-start items-center">
                <img src="./src/images/Facebook.png" alt="Facebook" class="bg-white rounded-full  max-w-10 max-h-10 mr-4">
                <img src="./src/images//X.png" alt="Twitter" class=" bg-white rounded-full max-w-10 max-h-10 mr-4">
                <img src="./src/images//insta.png" alt="Instagram" class=" bg-white rounded-full max-w-10 max-h-10 mr-4">
                <img src="./src/images/Youtube.png" alt="Youtube" class=" bg-white rounded-full max-w-10 max-h-10 mr-4">
            </div>
        </div>
        <div class="flex justify-center">
            <ul class="text-white text-xs flex flex-row flex-wrap justify-between max-w-96 ">
                <li class="pt-4 pr-2">Vie privée</li>
                <li class="pt-4 pr-2">Cookies</li>
                <li class="pt-4 pr-2"> Mentions légales</li>
                <li class="pt-4 pr-2"> Conditions d'utilisation</li>
                <li class="pt-4 pr-2">Accessibilité</li>
                <li class="pt-4 ">Configuration des cookies</li>
            </ul>
        </div>
        <div class=" flex justify-center">
            <p class="text-white text-xs max-w-96 text-center pt-10">LEGO System A/S, DK-7190 Billund, Denmark. Vous
                devez
                être
                âgé(e) d’au
                moins 18
                ans pour
                faire des achats en
                ligne. LEGO, le logo LEGO, la Minifigure, DUPLO, le logo FRIENDS, le logo MINIFIGURES, le DREAMZzz,
                NINJAGO,
                VIDIYO et MINDSTORMS sont des marques déposées du Groupe LEGO. ©2024 The LEGO Group. Tous droits
                réservés.
                L'utilisation de ce site implique que vous acceptez les conditions d'utilisation.</p>
        </div>

    </footer>