
<section class="w-card-size1 h-card-height1 bg-white p-4">
    <div class="bg-white p-4">
        <img src="./src/images/Button - Ajouter à la liste de cadeaux.png" alt="Coeur" class="">
        <img src="{{image_url}}" alt="Set Lego" class="">
    </div>
    <ul class="flex flex-row justify-between max-w-40 py-2">
        <li class="p-2"><img src="./src/images/Img - Âges_mask-group.png" alt="" class="max-w-5">10+
        </li>
        <li class="p-2"><img src="./src/images/Img - Nombre de pièces_mask-group.png" alt=""
                class="max-w-5">1229
        </li>
        <li class="p-2"><img src="./src/images/star_yellow_outline_and_flat - etoile.jpg" alt=""
                class="max-w-5 ">4.6
        </li>
    </ul>
    <h1 class="text-base font-bold p-1">{{name}}</h1>


    <h2 class="font-bold text-xl p-2">{{price}}€</h2>
    <button class="text-center bg-orange-600 rounded-full px-8 py-2 font-bold flex items-center hover:bg-transparent
    border-orange-600 border-2 border-solid">
        <img src="./src/images/Mask Group.png" alt="Panier" class="text-center ">Ajouter au Panier </img>
    </button>
</section>